blank_issues_enabled: true
contact_links:
  - name: Nobita Support
    url: https://t.me/Nobita_Supports
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    about: Documentation for getting started with bot.
